spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/rudkids?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      access:
        expire-length: 3600000 #1시간
      refresh:
        expire-length: 1210000000 #14일

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    oauth-end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes:
      - https://www.googleapis.com/auth/userinfo.profile
      - https://www.googleapis.com/auth/userinfo.email
    access-type: offline

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    oauth-end-point: https://kauth.kakao.com/oauth/authorize
    app-admin-key: f9831d648ad4a0b602209f819bb84b55
    account-uri: https://kapi.kakao.com/v2/user/me
    token-uri: https://kauth.kakao.com/oauth/token

sms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
    domain-uri: https://api.coolsms.co.kr
  info:
    sender:
      phone-number: ${SMS_SENDER_PHONE_NUMBER}

payment:
  toss:
    client-key: test_ck_ZORzdMaqN3wNmedjP7g85AkYXQGw
    secret-key: ${TOSS_PAYMENT_SECRET_KEY}

application:
  bucket:
    name: rudkids-image
  cloudfront:
    url: https://duu9477ot0it6.cloudfront.net/
  sub-domain:
    url: https://dev-img.rudkids.com/

cloud:
  aws:
    region:
      static: ap-northeast-2
    access-key: ${IAM_ACCESS_KEY}
    secret-key: ${IAM_SECRET_KEY}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
