spring:
  sql:
    init:
      mode: always
      platform: hibernate.dialect.MySQL8Dialect
      schema-locations: classpath:db/prod/schema.sql
      data-locations: classpath:db/prod/data.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_spl: true
        format_sql: true