spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform=org: hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/rudkids?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nswon0729@

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

security:
  jwt:
    token:
      secret-key: bmFtc2Utc3ByaW5nLWJvb3Qtand0LXNlY3JldA==
      access:
        expire-length: 3600000 #1시간
      refresh:
        expire-length: 1210000000 #14일

oauth:
  google:
    client-id: 727793852011-l9dk92pfd4l9hv43ldkt8c53ova8hcui.apps.googleusercontent.com
    client-secret: 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
    oauth-end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes:
      - https://www.googleapis.com/auth/userinfo.profile
      - https://www.googleapis.com/auth/directory.readonly
      - https://www.googleapis.com/auth/user.birthday.read
      - https://www.googleapis.com/auth/user.gender.read
      - https://www.googleapis.com/auth/user.phonenumbers.read
      - https://www.googleapis.com/auth/user.emails.read
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/profile.emails.read
    access-type: offline
    person-fields:
      - names
      - photos
      - genders
      - birthdays
      - emailAddresses
      - phoneNumbers
    key: AIzaSyAhJ-d-2DsR1uwtbXG2o5TitukPP1shxNs

  kakao:
    client-id: 60e95622dc0ddd18b407815d105fdb74
    oauth-end-point: https://kauth.kakao.com/oauth/authorize
    app-admin-key: f9831d648ad4a0b602209f819bb84b55
    account-uri: https://kapi.kakao.com/v2/user/me
    token-uri: https://kauth.kakao.com/oauth/token

sms:
  api:
    key: NCSXGQWD932OYAFZ
    secret: TQHAVI4N1Y22UTPT2HRA7RIQMOOZSSPN
    domain-uri: https://api.coolsms.co.kr

payment:
  toss:
    client-key: test_ck_ZORzdMaqN3wNmedjP7g85AkYXQGw
    secret-key: test_sk_Z0RnYX2w532Ld79ZObNrNeyqApQE
    confirm-uri: https://api.tosspayments.com/v1/payments/confirm