spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform=org: hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/rudkids?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nswon0729@

#  jwt:
#    access-token-valid-time: ${ACCESS_TOKEN_VALID_TIME}
#    refresh-token-valid-time: ${REFRESH_TOKEN_VALID_TIME}
#    secret: ${JWT_SECRET}
#
#oauth:
#  google:
#    base-url: ${GOOGLE_BASE_URL}
#    client-id: ${GOOGLE_CLIENT_ID}
#    client-secret: ${GOOGLE_CLIENT_SCERET}
#    redirect-url: ${GOOGLE_REDIRECT_URL}
#
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full
#
#mail-sender:
#  host: smtp.gmail.com
#  port: 587
#  username: ${MAIL_USERNAME}
#  password: ${MAIL_PASSWORD}
#  protocol: smtp
#  auth: true
#  starttls-enable: true
