spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform=org: hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/rudkids?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      access:
        expire-length: 3600000 #1시간
      refresh:
        expire-length: 1210000000 #14일

oauth:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    oauth-end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes:
      - https://www.googleapis.com/auth/userinfo.profile
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/directory.readonly
      - https://www.googleapis.com/auth/user.birthday.read
      - https://www.googleapis.com/auth/user.gender.read
      - https://www.googleapis.com/auth/user.phonenumbers.read
    token-uri: https://oauth2.googleapis.com/token
    access-type: offline
    people-uri: https://people.googleapis.com/v1/people/me?personFields=genders,birthdays,phoneNumbers&key=AIzaSyAhJ-d-2DsR1uwtbXG2o5TitukPP1shxNs

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    oauth-end-point: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    app-admin-key: f9831d648ad4a0b602209f819bb84b55
    account-uri: https://kapi.kakao.com/v2/user/me
    client-secret: ${KAKAO_CLIENT_SECRET}

sms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
    domain-uri: https://api.coolsms.co.kr