spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform=org: hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/rudkids?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

oauth:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    oauth-end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes:
      - https://www.googleapis.com/auth/userinfo.profile
      - https://www.googleapis.com/auth/userinfo.email
    token-uri: https://oauth2.googleapis.com/token
    access-type: offline

security:
 jwt:
  token:
    secret-key: bmFtc2Utc3ByaW5nLWJvb3Qtand0LXNlY3JldA==
    access:
      expire-length: 3600000 #1시간
    refresh:
      expire-length: 1210000000 #14일