spring:
  batch:
    job:
      name: ${job.name:NONE}
#    jdbc:
#      initialize-schema: always

  jpa:
    database: mysql
    database-platform=org: hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/rudkids?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: batchtest0729
    password: ${MALE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      batch: DEBUG
